
//
//  AndroidStyleKit.swift
//  ProjectName
//
//  Created by kohei on 2016/09/15.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class AndroidStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfAndroid: UIImage?
        static var androidTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawAndroid() {
        //// Color Declarations
        let fillColor = UIColor(red: 0.606, green: 0.719, blue: 0.221, alpha: 1.000)

        //// android.svg Group
        //// Group 2
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 278.36, y: 136.39))
        bezierPath.addLine(to: CGPoint(x: 68.78, y: 136.39))
        bezierPath.addCurve(to: CGPoint(x: 60.34, y: 144.84), controlPoint1: CGPoint(x: 64.12, y: 136.39), controlPoint2: CGPoint(x: 60.34, y: 140.17))
        bezierPath.addLine(to: CGPoint(x: 60.34, y: 320.58))
        bezierPath.addCurve(to: CGPoint(x: 68.78, y: 329.03), controlPoint1: CGPoint(x: 60.34, y: 325.25), controlPoint2: CGPoint(x: 64.12, y: 329.03))
        bezierPath.addLine(to: CGPoint(x: 106.14, y: 329.03))
        bezierPath.addLine(to: CGPoint(x: 106.14, y: 388.25))
        bezierPath.addCurve(to: CGPoint(x: 131.03, y: 413.14), controlPoint1: CGPoint(x: 106.14, y: 402), controlPoint2: CGPoint(x: 117.28, y: 413.14))
        bezierPath.addLine(to: CGPoint(x: 131.03, y: 413.14))
        bezierPath.addCurve(to: CGPoint(x: 155.91, y: 388.25), controlPoint1: CGPoint(x: 144.77, y: 413.14), controlPoint2: CGPoint(x: 155.91, y: 402))
        bezierPath.addLine(to: CGPoint(x: 155.91, y: 329.03))
        bezierPath.addLine(to: CGPoint(x: 190.71, y: 329.03))
        bezierPath.addLine(to: CGPoint(x: 190.71, y: 388.25))
        bezierPath.addCurve(to: CGPoint(x: 215.59, y: 413.14), controlPoint1: CGPoint(x: 190.71, y: 402), controlPoint2: CGPoint(x: 201.85, y: 413.14))
        bezierPath.addLine(to: CGPoint(x: 215.59, y: 413.14))
        bezierPath.addCurve(to: CGPoint(x: 240.48, y: 388.25), controlPoint1: CGPoint(x: 229.34, y: 413.14), controlPoint2: CGPoint(x: 240.48, y: 402))
        bezierPath.addLine(to: CGPoint(x: 240.48, y: 329.03))
        bezierPath.addLine(to: CGPoint(x: 278.36, y: 329.03))
        bezierPath.addCurve(to: CGPoint(x: 286.8, y: 320.58), controlPoint1: CGPoint(x: 283.02, y: 329.03), controlPoint2: CGPoint(x: 286.8, y: 325.25))
        bezierPath.addLine(to: CGPoint(x: 286.8, y: 144.84))
        bezierPath.addCurve(to: CGPoint(x: 278.36, y: 136.39), controlPoint1: CGPoint(x: 286.8, y: 140.17), controlPoint2: CGPoint(x: 283.02, y: 136.39))
        bezierPath.close()
        bezierPath.miterLimit = 4;

        fillColor.setFill()
        bezierPath.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: -0.02, y: 136.32, width: 49.75, height: 150.85), cornerRadius: 24.8)
        fillColor.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(roundedRect: CGRect(x: 297.43, y: 136.32, width: 49.75, height: 150.85), cornerRadius: 24.8)
        fillColor.setFill()
        rectangle2Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 70.47, y: 124.07))
        bezier2Path.addLine(to: CGPoint(x: 276.17, y: 124.07))
        bezier2Path.addCurve(to: CGPoint(x: 284.43, y: 113.87), controlPoint1: CGPoint(x: 281.53, y: 124.07), controlPoint2: CGPoint(x: 285.54, y: 119.13))
        bezier2Path.addCurve(to: CGPoint(x: 228.97, y: 38.33), controlPoint1: CGPoint(x: 277.63, y: 81.45), controlPoint2: CGPoint(x: 256.98, y: 54.12))
        bezier2Path.addLine(to: CGPoint(x: 246.55, y: 6.6))
        bezier2Path.addCurve(to: CGPoint(x: 244.82, y: 0.56), controlPoint1: CGPoint(x: 247.74, y: 4.46), controlPoint2: CGPoint(x: 246.97, y: 1.75))
        bezier2Path.addCurve(to: CGPoint(x: 238.77, y: 2.29), controlPoint1: CGPoint(x: 242.67, y: -0.63), controlPoint2: CGPoint(x: 239.96, y: 0.14))
        bezier2Path.addLine(to: CGPoint(x: 221.06, y: 34.26))
        bezier2Path.addCurve(to: CGPoint(x: 173.32, y: 23.76), controlPoint1: CGPoint(x: 206.54, y: 27.52), controlPoint2: CGPoint(x: 190.37, y: 23.76))
        bezier2Path.addCurve(to: CGPoint(x: 125.59, y: 34.26), controlPoint1: CGPoint(x: 156.27, y: 23.76), controlPoint2: CGPoint(x: 140.1, y: 27.52))
        bezier2Path.addLine(to: CGPoint(x: 107.87, y: 2.29))
        bezier2Path.addCurve(to: CGPoint(x: 101.82, y: 0.56), controlPoint1: CGPoint(x: 106.68, y: 0.14), controlPoint2: CGPoint(x: 103.97, y: -0.63))
        bezier2Path.addCurve(to: CGPoint(x: 100.09, y: 6.6), controlPoint1: CGPoint(x: 99.68, y: 1.75), controlPoint2: CGPoint(x: 98.9, y: 4.45))
        bezier2Path.addLine(to: CGPoint(x: 117.67, y: 38.33))
        bezier2Path.addCurve(to: CGPoint(x: 62.21, y: 113.87), controlPoint1: CGPoint(x: 89.66, y: 54.12), controlPoint2: CGPoint(x: 69.01, y: 81.44))
        bezier2Path.addCurve(to: CGPoint(x: 70.47, y: 124.07), controlPoint1: CGPoint(x: 61.11, y: 119.13), controlPoint2: CGPoint(x: 65.11, y: 124.07))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 234.7, y: 76.79))
        bezier2Path.addCurve(to: CGPoint(x: 225.13, y: 86.35), controlPoint1: CGPoint(x: 234.7, y: 82.07), controlPoint2: CGPoint(x: 230.41, y: 86.35))
        bezier2Path.addCurve(to: CGPoint(x: 215.57, y: 76.79), controlPoint1: CGPoint(x: 219.85, y: 86.35), controlPoint2: CGPoint(x: 215.57, y: 82.07))
        bezier2Path.addCurve(to: CGPoint(x: 225.13, y: 67.22), controlPoint1: CGPoint(x: 215.57, y: 71.5), controlPoint2: CGPoint(x: 219.85, y: 67.22))
        bezier2Path.addCurve(to: CGPoint(x: 234.7, y: 76.79), controlPoint1: CGPoint(x: 230.41, y: 67.22), controlPoint2: CGPoint(x: 234.7, y: 71.5))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 121.51, y: 67.22))
        bezier2Path.addCurve(to: CGPoint(x: 131.07, y: 76.79), controlPoint1: CGPoint(x: 126.79, y: 67.22), controlPoint2: CGPoint(x: 131.07, y: 71.5))
        bezier2Path.addCurve(to: CGPoint(x: 121.51, y: 86.35), controlPoint1: CGPoint(x: 131.07, y: 82.07), controlPoint2: CGPoint(x: 126.79, y: 86.35))
        bezier2Path.addCurve(to: CGPoint(x: 111.94, y: 76.79), controlPoint1: CGPoint(x: 116.23, y: 86.35), controlPoint2: CGPoint(x: 111.94, y: 82.07))
        bezier2Path.addCurve(to: CGPoint(x: 121.51, y: 67.22), controlPoint1: CGPoint(x: 111.94, y: 71.5), controlPoint2: CGPoint(x: 116.22, y: 67.22))
        bezier2Path.close()
        bezier2Path.miterLimit = 4;

        fillColor.setFill()
        bezier2Path.fill()
    }

    //// Generated Images

    public class var imageOfAndroid: UIImage {
        if Cache.imageOfAndroid != nil {
            return Cache.imageOfAndroid!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 347, height: 413), false, 0)
            AndroidStyleKit.drawAndroid()

        Cache.imageOfAndroid = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfAndroid!
    }

}
